// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAapZmTd06wQr4VzeKrM_CQki4ogWEik7E',
    appId: '1:619801676094:web:57198c29f39330aa88c46f',
    messagingSenderId: '619801676094',
    projectId: 'cosmatic-3b57d',
    authDomain: 'cosmatic-3b57d.firebaseapp.com',
    storageBucket: 'cosmatic-3b57d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBwK9PO1ekAEvg93O6Sq7rj7yrVCPC7N0',
    appId: '1:619801676094:android:58473a50e3ea315a88c46f',
    messagingSenderId: '619801676094',
    projectId: 'cosmatic-3b57d',
    storageBucket: 'cosmatic-3b57d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG7QF5tqkepAUvg-QQfqGIncoN5AKRgyE',
    appId: '1:619801676094:ios:7b1a0c3acd71b4d888c46f',
    messagingSenderId: '619801676094',
    projectId: 'cosmatic-3b57d',
    storageBucket: 'cosmatic-3b57d.appspot.com',
    iosBundleId: 'com.example.cosmatic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG7QF5tqkepAUvg-QQfqGIncoN5AKRgyE',
    appId: '1:619801676094:ios:7b1a0c3acd71b4d888c46f',
    messagingSenderId: '619801676094',
    projectId: 'cosmatic-3b57d',
    storageBucket: 'cosmatic-3b57d.appspot.com',
    iosBundleId: 'com.example.cosmatic',
  );
}
